name: 安全部署流程

# 关键修复1：添加严格的并发控制
concurrency:
  group: pages-deploy-${{ github.ref }}
  cancel-in-progress: false  # 禁止取消进行中的部署

on:
  repository_dispatch:
    types: [run_analysis]

jobs:
  analyze:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
      - uses: actions/checkout@v4

      # 关键修复2：添加部署前检查
      - name: 验证输入
        run: |
          if [ -z "${{ github.event.inputs.bvid }}" ]; then
            echo "错误：缺少bvid参数"
            exit 1
          fi

      - name: 执行分析
        env:
          BVID: ${{ github.event.inputs.bvid }}
        run: |
          python analyzer.py "$BVID"
          mkdir -p public
          cp output_*.json public/
          cp report_*.html public/

      # 关键修复3：添加部署健康检查
      - name: 验证生成文件
        run: |
          [ -f "public/output_${BVID}.json" ] || exit 1
          [ -f "public/report_${BVID}.html" ] || exit 1

      - name: 安全部署
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          force_orphan: true  # 强制独立部署
          keep_files: false   # 清理旧文件
          enable_jekyll: false # 禁用自动处理
