name: B站舆情分析

on:
  repository_dispatch:
    types: [run_analysis]
  workflow_dispatch:
    inputs:
      bvid:
        description: 'B站视频BV号'
        required: true

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          pip install -r scripts/requirements.txt
          
      - name: Run analysis
        env:
          BVID: ${{ github.event.inputs.bvid || github.event.client_payload.bvid }}
        run: |
          python scripts/analyzer.py "$BVID"
          
      - name: Upload results
        uses: actions/upload-artifact@v3
        with:
          name: analysis-results
          path: output_*
          
      - name: Commit results
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git pull
          git add output_*
          git commit -m "Add analysis results for $BVID"
          git push
