name: Python Analyzer
on: 
  workflow_dispatch:
    inputs:
      bvid:
        description: 'B站视频BV号'
        required: true

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: 设置Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 执行分析
        run: |
          cd private/analysis
          pip install -r ../../requirements.txt
          python analyzer.py "${{ github.event.inputs.bvid }}"
          # 将结果保存到公开目录
          mkdir -p ../../public
          cp output.json ../../public/

      - name: 部署结果
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
